from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import FileResponse
from dotenv import load_dotenv

from app.audit import init_audit_db, list_audit_events, record_approved_triage, record_triage
from app.jira import JiraConfigurationError, JiraRequestError, add_internal_comment, add_labels, add_public_comment, assign_team, get_jira_issue, list_pending_issues
from app.repository import load_dataset
from app.schemas import AutonomousConfirmation, AutonomousTriageResult, ApprovedTriageResult, AuditEvent, JiraCommentPreview, JiraCommentResult, JiraRoutingResult, PendingJiraIssue, PublishConfirmation, TicketInput, TriageDecision
from app.triage import make_decision


load_dotenv()
STATIC_DIR = Path(__file__).resolve().parent / "static"


@asynccontextmanager
async def lifespan(app: FastAPI):
    init_audit_db()
    app.state.dataset = load_dataset()
    yield


app = FastAPI(
    title="KRkRice Helpdesk Agent",
    version="0.1.0",
    description="Safe, synthetic IT helpdesk triage MVP.",
    lifespan=lifespan,
)


@app.get("/", include_in_schema=False)
def dashboard() -> FileResponse:
    return FileResponse(STATIC_DIR / "dashboard.html")


@app.get("/health")
def health(request: Request) -> dict[str, object]:
    dataset = request.app.state.dataset
    return {
        "status": "ok",
        "records": {name: len(rows) for name, rows in dataset.items()},
    }


@app.post("/api/triage", response_model=TriageDecision)
def triage(ticket: TicketInput, request: Request) -> TriageDecision:
    return make_decision(ticket, request.app.state.dataset)


@app.post("/api/jira/{issue_key}/triage", response_model=TriageDecision)
def triage_jira_issue(issue_key: str, request: Request) -> TriageDecision:
    try:
        issue = get_jira_issue(issue_key)
    except JiraConfigurationError as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc
    except JiraRequestError as exc:
        raise HTTPException(status_code=502, detail=str(exc)) from exc

    ticket = TicketInput(
        issue_key=issue["issue_key"],
        summary=issue["summary"],
        description=issue["description"],
        use_ai=True,
    )
    return make_decision(ticket, request.app.state.dataset)


def build_jira_preview(decision: TriageDecision) -> JiraCommentPreview:
    approved_sources = [match.record_id for match in decision.knowledge_matches if match.score >= 0.30]
    sources = ", ".join(approved_sources[:2]) or "None"

    if decision.decision == "respond":
        action = "add_internal_comment"
        comment = (
            "## AI triage preview\n\n"
            f"**Category:** {decision.category}\n"
            f"**Suggested team:** {decision.assigned_team_name}\n"
            f"**Confidence:** {decision.confidence:.0%}\n"
            f"**Knowledge sources:** {sources}\n\n"
            f"{decision.suggested_response}\n\n"
            "_Generated by the KRkRice helpdesk agent. Human review required._"
        )
    elif decision.decision == "escalate":
        action = "escalate"
        comment = (
            "## AI triage preview — escalation required\n\n"
            f"**Category:** {decision.category}\n"
            f"**Team:** {decision.assigned_team_name}\n"
            f"**Reason:** {decision.escalation_reason}\n\n"
            "_No automatic response was generated._"
        )
    else:
        action = "route_only"
        comment = (
            "## AI triage preview — routing only\n\n"
            f"**Category:** {decision.category}\n"
            f"**Suggested team:** {decision.assigned_team_name}\n"
            f"**Reason:** {decision.escalation_reason}\n\n"
            "_No sufficiently strong approved answer was found._"
        )

    return JiraCommentPreview(
        issue_key=decision.issue_key,
        action=action,
        comment=comment,
        will_write_to_jira=False,
    )


@app.post("/api/jira/{issue_key}/preview", response_model=JiraCommentPreview)
def preview_jira_action(issue_key: str, request: Request) -> JiraCommentPreview:
    return build_jira_preview(triage_jira_issue(issue_key, request))


@app.post("/api/jira/{issue_key}/publish-internal-comment", response_model=JiraCommentResult)
def publish_internal_comment(
    issue_key: str,
    confirmation: PublishConfirmation,
    request: Request,
) -> JiraCommentResult:
    # Pydantic enforces the explicit PUBLISH confirmation before this function runs.
    preview = preview_jira_action(issue_key, request)
    try:
        comment_id = add_internal_comment(preview.issue_key, preview.comment)
    except JiraConfigurationError as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc
    except JiraRequestError as exc:
        raise HTTPException(status_code=502, detail=str(exc)) from exc
    return JiraCommentResult(issue_key=preview.issue_key, comment_id=comment_id)


def label_slug(value: str) -> str:
    return "-".join(part for part in value.lower().replace("&", " ").split() if part)


@app.post("/api/jira/{issue_key}/publish-routing-labels", response_model=JiraRoutingResult)
def publish_routing_labels(
    issue_key: str,
    confirmation: PublishConfirmation,
    request: Request,
) -> JiraRoutingResult:
    decision = triage_jira_issue(issue_key, request)
    labels = [
        "ai-triaged",
        f"route-{label_slug(decision.category)}",
        f"team-{label_slug(decision.assigned_team_name.replace('KRkRice IT ', ''))}",
    ]
    try:
        added = add_labels(decision.issue_key, labels)
        assign_team(decision.issue_key, decision.assigned_team_id)
    except JiraConfigurationError as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc
    except JiraRequestError as exc:
        raise HTTPException(status_code=502, detail=str(exc)) from exc
    return JiraRoutingResult(issue_key=decision.issue_key, labels_added=added)


@app.get("/api/jira/pending", response_model=list[PendingJiraIssue])
def pending_jira_issues(limit: int = 10) -> list[PendingJiraIssue]:
    try:
        issues = list_pending_issues(limit)
    except JiraConfigurationError as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc
    except JiraRequestError as exc:
        raise HTTPException(status_code=502, detail=str(exc)) from exc
    return [PendingJiraIssue(**issue) for issue in issues]


@app.post("/api/jira/review-queue", response_model=list[JiraCommentPreview])
def review_jira_queue(request: Request, limit: int = 10) -> list[JiraCommentPreview]:
    try:
        issues = list_pending_issues(limit)
    except JiraConfigurationError as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc
    except JiraRequestError as exc:
        raise HTTPException(status_code=502, detail=str(exc)) from exc
    return [preview_jira_action(issue["issue_key"], request) for issue in issues]


@app.post("/api/jira/{issue_key}/approve-triage", response_model=ApprovedTriageResult)
def approve_jira_triage(
    issue_key: str,
    confirmation: PublishConfirmation,
    request: Request,
) -> ApprovedTriageResult:
    try:
        current_issue = get_jira_issue(issue_key)
    except JiraConfigurationError as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc
    except JiraRequestError as exc:
        raise HTTPException(status_code=502, detail=str(exc)) from exc
    if "ai-triaged" in current_issue.get("labels", []):
        raise HTTPException(status_code=409, detail="This issue has already been triaged.")

    decision = triage_jira_issue(issue_key, request)
    preview = build_jira_preview(decision)
    labels = [
        "ai-triaged",
        f"route-{label_slug(decision.category)}",
        f"team-{label_slug(decision.assigned_team_name.replace('KRkRice IT ', ''))}",
    ]
    try:
        comment_id = add_internal_comment(preview.issue_key, preview.comment)
        added = add_labels(preview.issue_key, labels)
        assign_team(preview.issue_key, decision.assigned_team_id)
    except JiraConfigurationError as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc
    except JiraRequestError as exc:
        raise HTTPException(status_code=502, detail=str(exc)) from exc
    record_approved_triage(
        issue_key=preview.issue_key,
        action=preview.action,
        category=decision.category,
        assigned_team_id=decision.assigned_team_id,
        assigned_team_name=decision.assigned_team_name,
        comment_id=comment_id,
        labels=added,
    )
    return ApprovedTriageResult(
        issue_key=preview.issue_key,
        action=preview.action,
        comment_id=comment_id,
        labels_added=added,
    )


def execute_autonomous_triage(issue_key: str, request: Request) -> AutonomousTriageResult:
    current_issue = get_jira_issue(issue_key)
    if "ai-triaged" in current_issue.get("labels", []):
        raise HTTPException(status_code=409, detail="This issue has already been triaged.")

    decision = triage_jira_issue(issue_key, request)
    preview = build_jira_preview(decision)
    labels = [
        "ai-triaged",
        "ai-autonomous",
        f"route-{label_slug(decision.category)}",
        f"team-{label_slug(decision.assigned_team_name.replace('KRkRice IT ', ''))}",
        f"decision-{decision.decision}",
    ]
    if decision.decision == "respond":
        resolution = (decision.suggested_response or "").split(": ", 1)[-1]
        comment = (
            "Hello,\n\n"
            f"Our IT helpdesk agent found an approved solution: {resolution}\n\n"
            "If this does not resolve the problem, reply to this ticket and the IT team will investigate.\n\n"
            "— KRkRice IT Helpdesk"
        )
        action = "add_public_comment"
        comment_id = add_public_comment(preview.issue_key, comment)
    else:
        action = preview.action
        comment = preview.comment.replace("Human review required.", "Published autonomously; available for review.")
        comment_id = add_internal_comment(preview.issue_key, comment)
    added = add_labels(preview.issue_key, labels)
    assign_team(preview.issue_key, decision.assigned_team_id)
    record_triage(
        issue_key=preview.issue_key,
        action=action,
        category=decision.category,
        assigned_team_id=decision.assigned_team_id,
        assigned_team_name=decision.assigned_team_name,
        comment_id=comment_id,
        labels=added,
        event_type="autonomous_triage",
    )
    return AutonomousTriageResult(
        issue_key=preview.issue_key,
        action=action,
        decision=decision.decision,
        confidence=decision.confidence,
        comment_id=comment_id,
        labels_added=added,
    )


@app.post("/api/jira/autonomous-run", response_model=list[AutonomousTriageResult])
def autonomous_jira_run(
    confirmation: AutonomousConfirmation,
    request: Request,
    limit: int = 10,
) -> list[AutonomousTriageResult]:
    try:
        issues = list_pending_issues(limit)
        return [execute_autonomous_triage(issue["issue_key"], request) for issue in issues]
    except JiraConfigurationError as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc
    except JiraRequestError as exc:
        raise HTTPException(status_code=502, detail=str(exc)) from exc


@app.get("/api/audit", response_model=list[AuditEvent])
def audit_events(limit: int = 50) -> list[AuditEvent]:
    return [AuditEvent(**event) for event in list_audit_events(limit)]
